//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace CompactDiscEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompactDisc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompactDisc()
        {
            this.trackList = new HashSet<Track>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string artist { get; set; }
        public Nullable<int> tracks { get; set; }
        public Nullable<decimal> price { get; set; }
        [JsonIgnore]
        [JsonProperty(Required = Required.Default)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Track> trackList { get; set; }
    }
}
