//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompactDiscEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int id { get; set; }
        public int cdId { get; set; }
        public string title { get; set; }
    
        public virtual CompactDisc compactDisc { get; set; }
    }
}
